### ISSUE TITLE
Audio externals: Wrong path to MaxAudioAPI.framework

### ISSUE THREAD

**Issue by lossius** [Cycling74/max-sdk#1]
In the Xcode project of source code for audio externals such as times~ the relative path to MaxAudioAPI.framework is provided as:

    ../../../c74support/msp-includes/MaxAudioAPI.framework

The correct should be

    ../../c74support/msp-includes/MaxAudioAPI.framework

**Comment by tap** [comment]
Hi @lossius -- I'm curious what has led to you asking about this path.  Is there perhaps some problem you are having with building the examples?

Having created a clean user account I can download the sdk zip from Github and run the Ruby build script with no problems -- including the build of the times~ object.

It looks like there is reference to MaxAudioAPI in at least some of the projects which is not used.  In the times~ project it is red because of the path issue that you raise, but this is merely cosmetic.  If this is the problem then it can be easily cleaned-up (and ignored in the mean time).
